name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: --timeout=2m --verbose

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20, 1.21, 1.22, 1.23]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: |
        go mod download
    - name: Test
      run: |
          go test -cover -race ./... -coverprofile=coverage.out
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v5
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Upload test results to Codecov
    #   if: ${{ !cancelled() }}
    #   uses: codecov/test-results-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}